import { createSlice } from "@reduxjs/toolkit";

/**
 * Redux slice for managing AI-powered search (GPT/Gemini) related state.
 * This includes toggling the search UI and storing movie search results.
 */
const gptSlice = createSlice({
  name: "AISearch", // The name of the slice, used in action types
  initialState: {
    isGptSearch: false, // Boolean to control the visibility of the GPT search interface
    movieSearchResults: [], // Array to store the results of AI-powered movie searches
  },
  reducers: {
    /**
     * Toggles the state of `isGptSearch` between true and false.
     * Used to show or hide the AI search component.
     * @param {object} state - The current state of the slice.
     */
    toggleGptSearch: (state) => {
      state.isGptSearch = !state.isGptSearch;
    },
    /**
     * Resets the AI search state, typically hiding the search interface.
     * @param {object} state - The current state of the slice.
     */
    resetSearch: (state) => {
      state.isGptSearch = false;
    },
    /**
     * Adds new movie search results to the `movieSearchResults` array.
     * The payload is expected to be an array of movie objects, each potentially including an `aiReason`.
     * @param {object} state - The current state of the slice.
     * @param {object} action - The action object containing the new movie results in `action.payload`.
     */
    addMovieSearchResults: (state, action) => {
      state.movieSearchResults = action.payload;
    },
    /**
     * Clears all movie search results from the `movieSearchResults` array.
     * @param {object} state - The current state of the slice.
     */
    clearMovieSearchResults: (state) => {
      state.movieSearchResults.length = 0;
    },
  },
});

// Export individual action creators generated by createSlice
export const {
  toggleGptSearch,
  resetSearch,
  addMovieSearchResults,
  clearMovieSearchResults,
} = gptSlice.actions;

// Export the reducer function to be combined with other reducers in the Redux store
export default gptSlice.reducer;
